version: '3'

services:
  normal:
    image: slam_docker/orb_slam3:latest
    build:
      context: ../
      dockerfile: ./dockerfile/orb_slam3.Dockerfile
    tty: true
    environment: # used inside a docker.
      - DEBUG=        
      - DISPLAY=${DISPLAY}
    container_name: orb_slam3
    network_mode: host
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/dri:/dev/dri #X11 stuff
      - /dev/snd:/dev/snd #X11 stuff
      # connect devices
    command: bash
  cuda:
    image: slam_docker/orb_slam3:latest
    build:
      context: ../
      dockerfile: ./dockerfile/orb_slam3.Dockerfile
    tty: true
    runtime: nvidia
    environment: # used inside a docker.
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DEBUG=        
      - DISPLAY=${DISPLAY}
    container_name: orb_slam3
    network_mode: host
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/dri:/dev/dri #X11 stuff
      - /dev/snd:/dev/snd #X11 stuff
      # connect devices
    command: bash -c 'cd ~/ORB_SLAM3 && . /opt/ros/melodic/setup.bash && export ROS_PACKAGE_PATH=${ROS_PACKAGE_PATH}:/root/ORB_SLAM3/Examples/ROS/ORB_SLAM3 && /bin/bash'